Info:
  Title: Postman API
  Description: A simple example ASP.NET Core Web API for testing Postman
  Version: v1
  Extensions: {}
Servers: []
Paths:
  /WeatherForecast:
    Operations:
      Get:
        Tags:
        - Name: WeatherForecast
          Extensions: {}
        Parameters: []
        Responses:
          200:
            Description: Success
            Headers: {}
            Content:
              text/plain:
                Schema:
                  Type: array
                  AllOf: []
                  OneOf: []
                  AnyOf: []
                  Required: []
                  Items:
                    AllOf: []
                    OneOf: []
                    AnyOf: []
                    Required: []
                    Properties: {}
                    AdditionalPropertiesAllowed: true
                    Enum: []
                    Extensions: {}
                    Reference:
                      Type: Schema
                      Id: WeatherForecast
                      IsLocal: true
                      ReferenceV3: '#/components/schemas/WeatherForecast'
                      ReferenceV2: '#/definitions/WeatherForecast'
                  Properties: {}
                  AdditionalPropertiesAllowed: true
                  Enum: []
                  Extensions: {}
                Examples: {}
                Encoding: {}
                Extensions: {}
              application/json:
                Schema:
                  Type: array
                  AllOf: []
                  OneOf: []
                  AnyOf: []
                  Required: []
                  Items:
                    AllOf: []
                    OneOf: []
                    AnyOf: []
                    Required: []
                    Properties: {}
                    AdditionalPropertiesAllowed: true
                    Enum: []
                    Extensions: {}
                    Reference:
                      Type: Schema
                      Id: WeatherForecast
                      IsLocal: true
                      ReferenceV3: '#/components/schemas/WeatherForecast'
                      ReferenceV2: '#/definitions/WeatherForecast'
                  Properties: {}
                  AdditionalPropertiesAllowed: true
                  Enum: []
                  Extensions: {}
                Examples: {}
                Encoding: {}
                Extensions: {}
              text/json:
                Schema:
                  Type: array
                  AllOf: []
                  OneOf: []
                  AnyOf: []
                  Required: []
                  Items:
                    AllOf: []
                    OneOf: []
                    AnyOf: []
                    Required: []
                    Properties: {}
                    AdditionalPropertiesAllowed: true
                    Enum: []
                    Extensions: {}
                    Reference:
                      Type: Schema
                      Id: WeatherForecast
                      IsLocal: true
                      ReferenceV3: '#/components/schemas/WeatherForecast'
                      ReferenceV2: '#/definitions/WeatherForecast'
                  Properties: {}
                  AdditionalPropertiesAllowed: true
                  Enum: []
                  Extensions: {}
                Examples: {}
                Encoding: {}
                Extensions: {}
            Links: {}
            Extensions: {}
        Callbacks: {}
        Security: []
        Servers: []
        Extensions: {}
    Servers: []
    Parameters: []
    Extensions: {}
Components:
  Schemas:
    WeatherForecast:
      Type: object
      AllOf: []
      OneOf: []
      AnyOf: []
      Required: []
      Properties:
        date:
          Type: string
          Format: date-time
          AllOf: []
          OneOf: []
          AnyOf: []
          Required: []
          Properties: {}
 